services:
    # sqlserver:
    #     image: mcr.microsoft.com/mssql/server:2019-latest
    #     environment:
    #         SA_PASSWORD: "TKjXDiZbAgKrNGIVVN9q"
    #         MSSQL_SA_PASSWORD: "TKjXDiZbAgKrNGIVVN9q"
    #         ACCEPT_EULA: "Y"
    #         MSSQL_PID: "Developer"
    #     ports:
    #         - "1433:1433"
    #     volumes:
    #         - sql_data:/var/opt/mssql

    postgres:
        image: postgres:15
        container_name: postgres-db
        environment:
            # Server=localhost;Port=5432;Database=colaboradorcruddb;User Id=crudapp;Password=TKjXDiZbAgKrNGIVVN9q;TrustServerCertificate=True;
            POSTGRES_USER: crudapp
            POSTGRES_PASSWORD: TKjXDiZbAgKrNGIVVN9q
            POSTGRES_DB: colaboradorcruddb
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    # aspnetapp:
    #     build:
    #         context: ./backend
    #         dockerfile: Dockerfile
    #     depends_on:
    #         - sqlserver
    #     ports:
    #         - "8000:80"
    #     environment:
    #         - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=ColaboradorCrud;User Id=SA;Password=TKjXDiZbAgKrNGIVVN9q;TrustServerCertificate=True;MultipleActiveResultSets=true;

volumes:
    postgres-data:
        driver: local
