# Reiniciar e buildar serviço específico:
# docker compose up -d --no-deps --build <service_name>

services:
    postgres:
        image: postgres:15
        container_name: postgres-db
        environment:
            POSTGRES_USER: crudapp
            POSTGRES_PASSWORD: TKjXDiZbAgKrNGIVVN9q
            POSTGRES_DB: colaboradorcruddb
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

    aspnetapp:
        build:
            context: ./backend
            dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
            - "8080:8080"

    angularapp:
        build:
            context: frontend
            dockerfile: Dockerfile
        ports:
            - 4200:80
        volumes:
            - ./frontend:/project
            - /project/node_modules

volumes:
    postgres-data:
        driver: local
